"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import socket

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-=6xftka72@rvc$3sla^92kxbjud(t362=-jy#2h^6q_941)!v4")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"
if DEBUG:
    env_path = BASE_DIR.parent / '.env'
    load_dotenv(dotenv_path=env_path)

if not DEBUG:
    # 1. Trust the ALB headers
    # The ALB terminates SSL and passes 'https' in this header
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # 2. Use forwarded headers for URL reconstruction
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True

    # 3. Security headers
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # 4. EXEMPT Health Check from SSL Redirect
    # Crucial: ALB health checks usually happen over HTTP to the private IP.
    # If redirected to HTTPS, the ALB might mark the instance as Unhealthy.
    SECURE_REDIRECT_EXEMPT = [
        r'^health/$', 
        r'^$',
    ]

    # 5. Host and Origin settings
    # We pull the actual domain (e.g., api.example.com) from ENV
    env_hosts = os.getenv('ALLOWED_HOSTS', '').split(',')
    ALLOWED_HOSTS = [host.strip() for host in env_hosts if host.strip()]

    # Internal Networking: Add the EC2 private IP to ALLOWED_HOSTS
    # This is required for the ALB to communicate with the instance via IP
    try:
        private_ip = socket.gethostbyname(socket.gethostname())
        if private_ip not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(private_ip)
    except Exception:
        pass

    # 6. CSRF Trusted Origins
    CSRF_TRUSTED_ORIGINS = [
        f"https://{host.strip()}" for host in ALLOWED_HOSTS 
        if not host.strip().replace('.', '').isdigit() # Exclude raw IPs
    ]
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cms",
    "catalog",
    "shop",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ecommerce.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'shop.context_processors.nav_items',
            ],
        },
    },
]

WSGI_APPLICATION = "ecommerce.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
    "ENGINE": "django.db.backends.mysql",
    "NAME": os.getenv("DB_NAME", "ecommerce_db"),
    "USER": os.getenv("DB_USER", "root"),
    "PASSWORD": os.getenv("DB_PASSWORD", "test"),
    "HOST": os.getenv("DB_HOST", "db"),
    "PORT": os.getenv("DB_PORT", "3306"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True



# The directory where you keep your source static files
STATIC_URL = '/static/'

# This is where Django will 'dump' the files
# It must result in /app/ecommerce/staticfiles
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- 2. Conditional Storage Logic ---
if DEBUG:
    # LOCAL DEVELOPMENT
    # Store uploads inside your static folder
    MEDIA_URL = 'media/' 
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

    # In Django 4.2+, explicitly define the local storage
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    # PRODUCTION (S3)
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
    
    # No query params in URLs (makes them cleaner/public)
    AWS_QUERYSTRING_AUTH = False 
    
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "location": "media", # Folder name inside S3 bucket
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "location": "static",
            },
        },
    }
    # URLs will point to S3
    MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/media/'
    STATIC_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/static/'
